apiVersion: v1
kind: Pod
metadata:
  name: sample-web-app-pod
  labels:
    app: sample-web-app
spec:
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /host/path
  - name: emptydir-volume
    emptyDir: {}
  hostNetwork: true
  securityContext:
    runAsUser: 1000
    seccompProfile:
      type: Unconfined
    windowsOptions:
      hostProcess: true
  initContainers:
  - name: init-container
    image: busybox:1.32.0
    command: ["sh", "-c", "echo Init Container is running"]
    securityContext:
      privileged: true
  containers:
  - name: web
    image: your-docker-username/sample-web-app:latest
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
      capabilities:
        add: ["CHOWN", "NET_ADMIN"]
  - name: web222
    image: your-docker-username/test:latest
    ports:
    - containerPort: 811
    securityContext:
      privileged: false
      windowsOptions:
        hostProcess: true
